@CatalogApi_HostAddress = http://localhost:9833

###

GET {{CatalogApi_HostAddress}}/products/{id}
Content-Type: application/json

###

GET {{CatalogApi_HostAddress}}/products/TestTime
Content-Type: application/json


###
POST {{CatalogApi_HostAddress}}/products
Content-Type: application/json
Accept:application/json

{
  "name": "Product 22",
  "price": 2222
}
###

GET {{CatalogApi_HostAddress}}/products
ContentType: application/json

###
